(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e=this||self;function f(a,b){a=a.split(".");var c=e;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};(class{constructor(a,b){this.g=b===g?a:""}}).prototype.toString=function(){return this.g.toString()};var g={};var h="function"===typeof Uint8Array;function l(){}let m;function n(a,b,c){a.i=null;m&&(b||(b=m),m=null);var d=a.constructor.s,k=a.constructor.m;k=d||k;b||(b=k?[d]:[]);a.j=k?0:-1;a.g=b;a:{if(b=a.g.length)if(--b,d=a.g[b],!(null===d||"object"!=typeof d||Array.isArray(d)||h&&d instanceof Uint8Array)){a.l=b-a.j;a.h=d;break a}a.l=Number.MAX_VALUE}a.o={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.l?(d+=a.j,a.g[d]=a.g[d]||p):(q(a),a.h[d]=a.h[d]||p)}const p=Object.freeze([]);function q(a){let b=a.l+a.j;a.g[b]||(a.h=a.g[b]={})}
function r(a,b){if(b<a.l){b+=a.j;var c=a.g[b];return c!==p?c:a.g[b]=[]}if(a.h)return c=a.h[b],c===p?a.h[b]=[]:c}function t(a,b){a=r(a,b);return null==a?a:!!a}function u(a,b){a=r(a,b);return null==a?0:a}function v(a){a=t(a,1);return null==a?!1:a}function w(a,b,c){b<a.l?a.g[b+a.j]=c:(q(a),a.h[b]=c)}function x(a,b,c,d){c!==d?w(a,b,c):b<a.l?a.g[b+a.j]=null:(q(a),delete a.h[b])}function y(a,b,c){a.i||(a.i={});if(!a.i[c]){let d=r(a,c);d&&(a.i[c]=new b(d))}return a.i[c]}
function z(a){if(a.i)for(var b in a.i){var c=a.i[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&z(c[d]);else c&&z(c)}return a.g}function A(a,b){m=b=b?JSON.parse(b):null;a=new a(b);m=null;return a}l.prototype.toString=function(){return z(this).toString()};var C=class extends l{constructor(a){super();n(this,a,B)}},B=[17];var E=class extends l{constructor(a){super();n(this,a,D)}},D=[8];var G=class extends l{constructor(a){super();n(this,a,F)}},F=[27];var H=class extends l{constructor(){super();n(this,void 0,null)}};var I=class extends l{constructor(a){super();n(this,a,null)}};var K=class extends l{constructor(a){super();n(this,a,J)}},J=[1,2,3];var M=class extends l{constructor(){super();n(this,void 0,L)}},L=[12];var N={};var O=class{};class P extends O{constructor(a){super();if(N!==N)throw Error("Bad secret");this.g=a}toString(){return this.g}};var Q="href rel src srcdoc action formaction sandbox cite srccite poster icon style".split(" ");(function(a){if(!Array.isArray(a)||!Array.isArray(a.raw))throw new TypeError("safeAttr is a template literal tag function and should be called using the tagged template syntax. For example, safeAttr`foo`;");const b=a[0].toLowerCase();Q.forEach(c=>{if(0===c.indexOf(b))throw Error(`Prefix '${a[0]}' does not guarantee the attribute `+"to be safe as it is also a prefix for "+`the security sensitive attribute '${c}'. `+"Please use native or safe DOM APIs to set the attribute.");});return new P(b)})`x-`;function R(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function aa(a){if(isNaN(a))return Math.random;const b=new ba(1E3+a);S(b);S(b);return()=>S(b)}function S(a){a.seed^=a.seed<<13;a.seed^=a.seed>>17;a.seed^=a.seed<<5;return(a.seed>>>0)/4294967296}class ba{constructor(a){this.seed=a}};function T(a,b){b=new CustomEvent(b);a.body.dispatchEvent(b)}
var ca=class{constructor(a){this.body=a;var b=R(a,"sampling_mod");this.g=b?Number(b):NaN;b=R(a,"namespace");if(!b){b="ns-"+aa(this.g)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));
a=document.createElement("META");a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}}addEventListener(a,b){this.body.addEventListener(a,b)}};function U(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function V(a){if(1>=a.h.offsetWidth||1>=a.h.offsetHeight)return!1;a.g.remove();T(a.context,"spanReady");return!0}
var da=class{constructor(a,b){this.context=a;this.i=b;this.h=U("SPAN");this.g=U("DIV");this.h.style.fontSize="6px";this.h.textContent="go";this.g.style.position="absolute";this.g.style.top="100%";this.g.style.left="100%";this.g.style.width="1px";this.g.style.height="0";this.g.style.overflow="hidden";this.g.style.visibility="hidden";this.g.appendChild(this.h)}wait(){if(!v(this.i)&&(T(this.context,"spanStart"),this.context.body.appendChild(this.g),!V(this)))return new Promise(a=>{const b=setInterval(()=>
{V(this)&&(clearInterval(b),a())},u(this.i,3))})}};var ea=class{constructor(a){this.h=0;this.i=y(a,G,1);this.g=y(a,E,12)||new E;this.h=a=u(a,2);2===a&&(w(this.g,6,!1),w(this.g,7,!1));y(this.i,C,10)||new C}};function W(a){a.g&=-31}function X(a,b){a.g|=b}var fa=class{constructor(a,b){this.context=a;this.i=b;new M;this.g=0}execute(){}};function Y(a){const b=A(K,R(a.context.body,"engine_msg")||"[]");return a.g.execute(b,void 0,void 0)||Promise.resolve()}function ha(a){var b;W(a.g);X(a.g,1);null===(b=window.AFMA_Communicator)||void 0===b?void 0:b.addEventListener("onshow",()=>{X(a.g,32)});let c=0;const d=a.context.body;d.addEventListener("browserRender",()=>{++c;if(1===c)T(a.context,"overallStart"),Y(a).then(()=>{T(a.context,"overallQuiet")});else{var k=d.clientHeight;d.clientWidth&&k&&Y(a)}})}
var ia=class{constructor(a,b,c){this.context=new ca(a);this.g=c(this.context,b)}};function ja(a){a.i.length=0;a.h=!0}function Z(a,b){a.g=!0;const c=()=>{a.h=!1;const d=a.i.shift();return void 0===d?(a.g=!1,Promise.resolve()):Z(a,d())};return b?b.then(c,()=>{if(a.h)return c();a.g=!1;return Promise.reject()}):c()}function ka(a,b){for(const c of b)a.i.push(c);if(!a.g)return Z(a)}var la=class{constructor(){this.h=this.g=!1;this.i=[]}};var ma=class extends fa{constructor(){super(...arguments);this.h=new la}execute(){ja(this.h);return ka(this.h,[()=>{},()=>{let a;var b=this.i;const c=new H;x(c,3,100,0);x(c,4,1E4,0);t(b.g,4)?(x(c,6,!0,!1),x(c,7,"monospace",""),x(c,8,"IMWimw0.!?@","")):(t(b.g,5)&&x(c,9,!0,!1),x(c,5,!0,!1));t(b.g,3)&&x(c,2,!0,!1);2===b.h&&x(c,2,!0,!1);c&&(a=(new da(this.context,c)).wait());T(this.context,"browserStart");T(this.context,"browserStartEnd");W(this);X(this,2);return a},()=>{T(this.context,"browserReady");
T(this.context,"browserReadyEnd");X(this,4);T(this.context,"overallReady")},()=>{T(this.context,"browserQuiet");T(this.context,"browserQuietEnd");X(this,8)}])}};(function(a){let b=null;f("mys.engine.init",(c,d)=>{c=A(I,R(d,"render_config")||"[]");b=new ia(d,c,a);ha(b)});f("mys.engine.stage",()=>b?b.g.g:0)})(function(a,b){b=new ea(b);return new ma(a,b)});}).call(this);
